version: "3.9"

networks:
  aspnet_network:
    driver: bridge
    
services:
  app: 
    container_name: aspnet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Src/CarDealership.Web/appsettings.json:/app/appsettings.json
    ports:
      - '80:80'
    networks:
      - aspnet_network
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CompanyDB
    ports:
      - "5432:5432"
    networks:
      - aspnet_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pgdata:/docker-entrypoint-initdb.d
volumes:
  postgres-data: